# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

symm_distance_matrix <- function(m1, phi_vector) {
    .Call('_labgpbart_symm_distance_matrix', PACKAGE = 'labgpbart', m1, phi_vector)
}

distance_matrix <- function(m1, m2, phi_vector) {
    .Call('_labgpbart_distance_matrix', PACKAGE = 'labgpbart', m1, m2, phi_vector)
}

